### ISSUE TITLE
[Feature Request] commands with multiple possible responses

### ISSUE THREAD

**Issue by RidoKilos** [otothea/botisimo#1]
Impractical Example
`!roshambo` might return `rock!`, `paper!`, or `scissors!`

Responses pulled from pool randomly or potentially with fixed chance. For more complexity you could make certain response chances more likely for user level; follower vs subscriber vs moderator

**Comment by otothea** [comment]
Added a new response variable called `pick`

example usage: `$(pick rock! | paper! | scissors!)`
