### ISSUE TITLE
Permission/role separation between Twitch chat and Discord servers

### ISSUE THREAD

**Issue by RidoKilos** [otothea/botisimo#3]
Probably requires an entirely new take on the situation since "moderator" and "subscriber don't necessarily translate to discord and "coolguys" and "admins" wouldn't for twitch.

**Comment by RidoKilos** [comment]
> instead of setting discord roles for each command in botisimo, the command permission options would remain as they are: everyone, subscriber, moderator, admin (owner) 
+
> you would have a new global setting to map your discord roles to the botisimo permission options

**Comment by otothea** [comment]
Added a place to map your Discord roles to moderator/subscriber roles in Botisimo

[Configure Discord Roles](https://botisimo.com/account/discord/roles)
