### ISSUE TITLE
Allow commands to set/use timers in discord chat

### ISSUE THREAD

**Issue by RidoKilos** [otothea/botisimo#4]
Example:
`!timer 5m Rido don't forget GW!`
Sets a timer to post "Rido don't forget GW!" every five minutes. Repeating the timer or maybe typing `!timer-` ends it.

**Comment by RidoKilos** [comment]
Alternatively, the timers could be prepped in botisimo.com's timer section before hand and simply turned on/off with their specific command:
`!rido-gw`

**Comment by otothea** [comment]
Owners and Moderators can now create a start/stop timers from the chat

[How to use !timer command](https://botisimo.com/docs/timers)
