### ISSUE TITLE
[Feature Request] Add specific "!raffle" command for chat viewers to join in

### ISSUE THREAD

**Issue by RidoKilos** [otothea/botisimo#5]
Could probably be custom command as well so that I can troll chat.

**Comment by otothea** [comment]
what if i did something like `!winner [keyword=]`, so that if you specify a keyword (or an entire phrase?) you filter by people who typed the keyword in the last 10 minutes or something like that.

**Comment by otothea** [comment]
i have taken your silence as a yes and did it the way i proposed.
