### ISSUE TITLE
[Feature request] !game and !title commands so that Mods can change stream details?

### ISSUE THREAD

**Issue by RidoKilos** [otothea/botisimo#6]
Fairly certain this is possible. Gonna dig for some evidence and/or API details

**Comment by otothea** [comment]
I added the `!title` and `!game` commands, the catch is, I had to add an extra permission request to the Twitch auth. So you will need to log out and reauth with Twitch to allow Botisimo to edit your channel. If simply logging out doesn't work, you may need to just completely unlink and relink your Twitch account in the `connections` section of your account.
