### ISSUE TITLE
add followers, subs, chat, etc to [target] option 

### ISSUE THREAD

**Issue by shawnbutts** [otothea/botisimo#87]
i'd like to be able to give subs XXXX currency.
i'd like to reward everyone currently in chat XX currency.
etc.
etc.

**Comment by otothea** [comment]
you can use these options now
- `!give 100 chat` (give all users in chat)
- `!give 100 subscribers` (give all users in chat that are subscribers)
- `!give 100 followers` (give all users in chat that are followers)
